apiVersion: v1
kind: ServiceAccount
metadata:
  name: smart-agent-reader
  namespace: smart-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: smart-agent-reader-role
  namespace: smart-agent
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps"]
  verbs: ["get", "list", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: smart-agent-reader-rolebinding
  namespace: smart-agent
subjects:
- kind: ServiceAccount
  name: smart-agent-reader
  namespace: smart-agent
roleRef:
  kind: Role
  name: smart-agent-reader-role
  apiGroup: rbac.authorization.k8s.io
